# Generated by Django 6.0.5 on 2026-05-24 19:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('eng', 'English'), ('sci', 'Science'), ('bio', 'Biology'), ('phy', 'Physics'), ('chem', 'Chemistry'), ('geo', 'Geography'), ('hist', 'History'), ('other', 'Other')], max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('correct_text_answer', models.TextField(blank=True)),
                ('solution_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('test', 'Test'), ('assignment', 'Weekly Assignment'), ('assessment', 'Weekly Assessment')], max_length=20)),
                ('answer_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('typed', 'Typed Answer'), ('typed_with_image', 'Typed + Image Upload')], default='mcq', max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('num_questions', models.IntegerField(default=10)),
                ('randomise', models.BooleanField(default=True)),
                ('randomise_values', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('show_results', models.BooleanField(default=False)),
                ('show_solution', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='classes.class')),
                ('questions', models.ManyToManyField(blank=True, to='assessments.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_order', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_answer', models.TextField(blank=True)),
                ('uploaded_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.FloatField(default=0)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionbank')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.questionchoice')),
                ('student_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.studentassessment')),
            ],
        ),
    ]
